### PR TITLE
added linux qvm support

### PR DESCRIPTION
**Pull request by Kr3m**
This will allow people to build qvm files from Linux, but you may have to add any additional source files that are not present in build/linux-qvm.  Should be self-explanatory, but feel free to reach out if you need assistance.

### CODE REVIEW

**Comment by briancullinan2** [comment]
Hey thanks! I think build.yml uses make/game_multi.make I adopted from another project.

**Comment by Kr3m** [comment]
Hey no problem.  I'm going to create a separate pull request in case you're interested that fixes missing files from srcs.mk, but I'm getting the following output when I try building it:

```vm/cgame/cg_atmospheric.asm:808 error: symbol BG_GetSkyHeightAtPoint undefined
vm/cgame/cg_atmospheric.asm:835 error: symbol BG_GetSkyGroundHeightAtPoint undefined
vm/cgame/cg_atmospheric.asm:1315 error: symbol BG_GetSkyGroundHeightAtPoint undefined
vm/cgame/cg_atmospheric.asm:1521 error: symbol BG_GetSkyGroundHeightAtPoint undefined
vm/cgame/cg_atmospheric.asm:2599 error: symbol BG_GetSkyHeightAtPoint undefined
vm/cgame/cg_atmospheric.asm:2626 error: symbol BG_GetSkyGroundHeightAtPoint undefined
vm/cgame/cg_atmospheric.asm:2997 error: symbol BG_GetSkyGroundHeightAtPoint undefined
vm/cgame/cg_atmospheric.asm:3286 error: symbol BG_GetSkyGroundHeightAtPoint undefined
vm/cgame/cg_atmospheric.asm:5399 error: symbol BG_LoadTraceMap undefined
make: *** [Makefile:27: vm/cgame.qvm] Error 9```

**Comment by Kr3m** [comment]
Or hmmm.  I guess if I pushed the changes to my fork, the pull request is updated automatically?

**Comment by Kr3m** [comment]
I've noticed make seems to work fine from your linux directory, but cg_atmospheric doesn't build.  I guess you do have a qvm solution though is what you were saying?  I noticed a qvm directory when running make, but there are no qvms located in it.  Probably due to the above mentioned bug.

**Comment by briancullinan2** [comment]
Add that file to your build file? Also needs something in game/bg_*, or try
to turn off the compile flag in the header file.

**Pull request closed without merging**
